services:
  django:
    container_name: django
    build:
      dockerfile: app/back-end/Dockerfile
    restart: always
    volumes:
      - ../halimus:/app
      - ../front-end/assets/:/usr/share/nginx/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env

    depends_on:
      - postgre
  postgre:
    container_name: postgre
    image: postgres:latest
    ports:
    - "5432:5432"
    env_file:
      - ./.env

  frontend:
    build:
      context: ../
      dockerfile: docker/app/front-end/Dockerfile
    container_name: frontend
    ports:
      - "8001:8001"
    depends_on:
      - django
    volumes:
      - ../front-end/assets/:/usr/share/nginx/static  # statik dosyaları yönlendiriyoruz

volumes:
  postgres_data:



