services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: app/back-end/Dockerfile
    restart: always
    volumes:
      - ../halimus:/app
      - ../front-end/:/usr/share/nginx/static
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DJANGO_DEBUG=True
    depends_on:
      postgre:
        condition: service_healthy
  
  postgre:
    container_name: postgre
    image: postgres:latest
    ports:
    - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}", "-d", "${DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 2s 

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--port", "6380"]
    ports:
      - "6380:6380"

  frontend:
    build:
      context: ../
      dockerfile: docker/app/front-end/Dockerfile
    container_name: frontend
    ports:
      - "8001:8001"
    depends_on:
      - django
    volumes:
      - ../front-end/:/usr/share/nginx/static

volumes:
  postgres_data:
